### PR TITLE
Losslessly compressed images to speed up site

### PR DESCRIPTION
**Pull request by tinakumar**

### CODE REVIEW

**Comment by natsteinmetz** [comment]
Could you also take care of the images on the about, connect, how and team pages? Those are the ones that are especially slow in loading right now. And is there a reason for (only?) compressing two of the team pictures?

**Comment by tinakumar** [comment]
This should be good to go. Something was wacky last time I ran the page insights because those were the only ones that had come up. Not this time! :)

**Comment by natsteinmetz** [comment]
@tinakumar This is not really the wanted result: at least some of the pictures have changed in size (width/height). You can see the result of that in this image for example:

screen shot 2016-06-15 at 1 06 06 pm

Then other files have been reduced in quality to the extent that they are not viable on the page. For example:
screen shot 2016-06-15 at 1 23 15 pm

The idea is to losslessly compress the images, meaning they neither change in their dimensions, nor in the quality. Looking at the original site, using Dev Tool's Page Speed analyzer, it doesn't offer to losslessy compress many of the pictures you have compressed. Not sure why they have been showing up for you in Page Speed...

Regarding the big header images, maybe you'll need to use an external tool to compress those without changing their dimensions. While speed is important, it is also important to keep the dimensions and the quality of the images as is.

**Comment by natsteinmetz** [comment]
Hey Tina, is this still something you would like to look at at some point, or shall I re-assign the task? Thanks! :)

**Pull request closed without merging**
