### PR TITLE
Updating Forms for Resources and Guides - Update application level fonts

### PR DESCRIPTION
**Pull request by rmoshier**
Hello! Here is my updated work for the 'Bootstrap styling for forms. Create/update forms for resources and guides.' card. A couple of comments/questions:

- I think the navbar cuts off the 'New Resource' title on the new resource form page. (I also think this is why the title bumps up right against the top nav.)
- I didn't focus on the other parts of the Resources, show, etc. because the card didn't specify. 
- Can't make description box bigger because is labeled as text in schema. Not sure if we want that changed. 
- Not sure which fonts should be used where. If you let me know I can do the quick fix, but if someone else wants to fix that is OK. 

For any of the above items, I'm happy to do the edits needed to make then happen. However, I wanted to check in first in case it is more appropriate for someone else to take that on. 

I'm very open to any other feedback you have. Thank you! :smile:

### CODE REVIEW

**Comment by rmoshier** [comment]
Also, looks like I'll need to pull from master before this can be merged. I'll take care of that after taking care of any feedback folks have.

**Comment by tinakumar** [comment]
@rmoshier You can use Archer Bold for the labels and then Archer Light for the form fields. Thanks for checking. :) The navbar is fixed to the top so we need to add some padding about the New Resource so that it doesn't get cut off. I believe they suggest 50px but you can play around with it. Yes, you don't have to worry about the show pages that is a separate story. :)

**Comment by natsteinmetz** [comment]
@rmoshier Could you also update the styling on the resource and guide edit html page? Thanks! (And last comment ;) )

**Comment by natsteinmetz** [comment]
@rmoshier or @tinakumar Can you please merge this? Thanks!

**Pull request merged**
