### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by brigid2718**
I think the spacing for each section could use a little work (for the headers at least).  I didn't have any of the images so I used placekittens.  (I also used some BowieIpsum for the description text, in case that looks weird.)

Let me know what you think!  I think it will look better once the site font is incorporated!

### CODE REVIEW

**Comment by natsteinmetz** [comment]
Yes, we can review the spacing later, and check how it all looks with the updated font! Overall it looks great!

Two comments only:
- can you invert the colors in the advisor tooltips, i.e. the background green and the border white?
- the placement of new team members (if you add for example two more) gets 'wonky', they shift around and don't keep their position. Maybe just play around with adding more members and see what happens? If it is easier, we can for now just put them in rows of 4 each, and if a row is not full, then it is not full... What do you think is easier?

**Comment by brigid2718** [comment]
Sure, I can invert the colors on the advisor dots.

As for the rows of dots, I used Bootstrap's grid system for the
medium-sized display, so each dot in the row needs to have a class name
that reflects the length of the row (col-md-4 if there are 3 dots in the
row because 12/4=3, col-md-3 if there are 4 dots in the row, etc...).  If
you wanted to add two more dots to the team list as it is, you'd have to
change the class of the 3 dots in the last row to col-md-3 and then add one
dot with that class, and then add one more dot with a col-md-12 class, and
it would be by itself centered in the next row.

I'd shy away from adding the actual row divs between the rows, because I
tried to make it responsive.

I could leave some notes in the documentation about editing this page
(that's not ideal, I don't think it should be so complicated),
alternatively, I could go the route of using javascript to determine the
bootstrap class names based on the number of "team-member" or "advisor"
divs in the list.

**Comment by natsteinmetz** [comment]
Just to make sure: don't invert the color on the dots, but on the pop-up with the detailed information about a person.

Regarding the rows of dots: the solution using Javascript seems to be the least complicated and the most expandable and clean...

**Comment by brigid2718** [comment]
Cool, I'll start working on that stuff when I can over the next few days!
Thanks for your feedback!

**Comment by natsteinmetz** [comment]
Nice! :) And you're welcome!

I will merge this branch, and you can just create another one with the updates. It will be nice to have this core page in there already until then. Thanks! :)

**Pull request merged**
